# Generated by Django 4.1.6 on 2023-02-14 04:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_user_first_name_alter_user_follower_set"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="following_set",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
